### ISSUE TITLE
Chapter 13 exercise 11

### ISSUE THREAD

**Issue by sohuwo** [williamgherman/c-solutions#14]
After (*s++==*t++),  return *s-*t is error, it maybe return * (s--)- *( t--)

**Comment by williamgherman** [comment]
Great find! I think the use of `(*s++ == *t++)` was overall too confusing, so I modified the loop to just increment after each pass. Will fix and commit.

**Comment by Filip013** [comment]
You use the subscript i that you never declared. You should use *s instead.
