### ISSUE TITLE
Exercise 4.09

### ISSUE THREAD

**Issue by tambow44** [williamgherman/c-solutions#2]
c) is incorrect.
You have stated:
0 -1 3

When in reality it is:
2 -1 3

Per code (any standard):

#include <stdio.h>

int main(void)
{
   int i, j, k;

   i = 1; j = 2; k = 3;
   i -= j -= k;
   printf("%d %d %d\n", i, j, k);

   return 0;
}

More specifically, per KN Kings site:
http://knking.com/books/c2/answers/c4.html

**Comment by williamgherman** [comment]
@tambow44 Well spotted. Double negative typo on my part. Will fix and resolve.
