### ISSUE TITLE
Exercise 6.08 is slightly incorrect

### ISSUE THREAD

**Issue by haydendavenport** [williamgherman/c-solutions#5]
The solution to 6.08 reads:

> Solution
> 
> The program will print 10 1 then print an endless stream of 1 s. The postfix increment operator in the print statement will always cause the conditional in the for loop to return true.

However, the program will actually print `10 5 3 2` followed by an endless stream of `1`s.

**Comment by williamgherman** [comment]
@haydendavenport Well spotted, fixing now.
