### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by haydendavenport** [williamgherman/c-solutions#7]
Minor errors, but:
**7.10:**
```Your sentence continas %d vowels.```

should read:
```Your sentence contains %d vowels.```

**7.14 (readme):**
```floating-poing```

should read:
```floating-point```

**10.02 (readme):**
```(b) a (parameter), b and c (local to g) (c) a (declared in block), b, c (local to g) and d```

should read:
```
(b) a (parameter), b and c (local to g) 
(c) a (declared in block), b, c (local to g) and d
```

**Comment by williamgherman** [comment]
@haydendavenport Thanks for finding these typos, will fix.
