### ISSUE TITLE
chapter 12 excecise 17:the pointer p level is not equal to the pointer a

### ISSUE THREAD

**Issue by sohuwo** [williamgherman/c-solutions#8]
maybe changed as follow:
int sum_2_dimensional_array(const int a[][LEN], int n)
{
        const int *p;
        int sum =0;

	for (p = *a; p < *a + n * LEN; p++)
		sum += *p;
	return sum;
}

**Comment by williamgherman** [comment]
Good catch! Thank you, will update.
